services:

  fastapi:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      REDIS_HOST: "redis"
    depends_on:
      - redis
      - minio
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  celery:
    build:
      context: .
    container_name: celery_worker
    depends_on:
      - fastapi
      - redis
      - minio
    environment:
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      REDIS_HOST: "redis"
    command: celery -A celery_app.celery_app worker --loglevel=info

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data   # optional: make Redis persistent too

  minio:
    image: minio/minio
    container_name: minio_server
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data   # ðŸ”¥ persistent MinIO storage


# -----------------------------------------
# VOLUMES (Created automatically by Docker)
# -----------------------------------------
volumes:
  minio_data:     # stores all uploaded files safely
  redis_data:     # optional (stores redis data if needed
